name: Mental health check
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  mental-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: egrzeszczak/mental-health-action@v1
