name: 'Dependency package audit'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
    - name: actions/checkout
      uses: actions/checkout@v3
    - name: npm audit action
      uses: oke-py/npm-audit-action@v2.3.0

